/**
 * Render the fixture deck to HTML for eyeballing, without a database, an
 * engine, or a browser:
 *
 *     pnpm --filter @tempo/reports try:deck [out.html] [awareness|gmv|install]
 *
 * Uses the checked-in instant-tier engine output
 * (`deck/fixtures/engine-content.gmv.instant.json`, regenerated by
 * `tempo-engine/scripts/dump_deck_fixture.py`) and the day-grain dashboard
 * fixture. Open the result in a browser and print to PDF at 16:9 to see what
 * the route produces.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { BriefObjective, isBriefObjective } from '@tempo/core';
import { buildDeckModel } from '../deck/build.js';
import { parseEngineContent } from '../deck/engine-content.js';
import { buildDashboardFixture } from '../deck/fixtures/dashboard.js';
import { renderDeckHtml } from '../deck/render.js';
import { defaultReportSpec } from '../deck/spec.js';

const out = process.argv[2] ?? 'deck.html';
const objectiveArg = process.argv[3] ?? BriefObjective.Gmv;
const objective = isBriefObjective(objectiveArg) ? objectiveArg : BriefObjective.Gmv;

const raw = JSON.parse(
  readFileSync(
    fileURLToPath(new URL('../deck/fixtures/engine-content.gmv.instant.json', import.meta.url)),
    'utf8',
  ),
) as unknown;

const parsed = parseEngineContent(raw);
const model = buildDeckModel({
  content: parsed.content,
  contentVersion: parsed.version,
  dashboard: buildDashboardFixture(),
  spec: defaultReportSpec(objective),
  objective,
  runId: parsed.content.findings[0]?.tenant_id ?? 'run_local_preview',
  tier: parsed.content.tier,
  generatedAt: new Date().toISOString(),
  windowDays: 7,
});

writeFileSync(out, renderDeckHtml(model), 'utf8');
console.log(
  `wrote ${out} — ${model.slides.length} slides, tier ${model.meta.tier}, ` +
    `${model.meta.fallbacks.length} fallback note(s)`,
);
