"""Write `BriefContentV2`'s JSON Schema to `contracts/brief_content_v2.schema.json`.

This file is the boundary contract in the literal sense: the TypeScript mirror
in `packages/reports/src/deck/engine-content.ts` validates itself against it
(`engine-content.drift.test.ts`), and `tests/test_content_schema_export.py`
fails when it drifts from the Pydantic model. Same mechanism as the METRICS
catalog port that already guards the other direction of this boundary — a
brief whose shape the renderer cannot read is a build failure, not a 502 in
production.

The two repos are co-located (`tempo-engine/` inside `dna160/buzzobot`), so
both checks run in one CI job with no cross-repo fetch.

Usage: `uv run python scripts/export_content_schema.py [--check]`
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from engine.contracts.content import BriefContentV2  # noqa: E402

SCHEMA_PATH = Path(__file__).resolve().parents[1] / "contracts" / "brief_content_v2.schema.json"


def render_schema() -> str:
    schema = BriefContentV2.model_json_schema()
    schema["$comment"] = (
        "Generated by scripts/export_content_schema.py — do not edit by hand. "
        "Regenerate after changing engine/contracts/content.py."
    )
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit non-zero if the file is stale")
    args = parser.parse_args()

    rendered = render_schema()
    if args.check:
        current = SCHEMA_PATH.read_text(encoding="utf-8") if SCHEMA_PATH.exists() else ""
        if current != rendered:
            print(f"{SCHEMA_PATH} is stale — run: uv run python scripts/export_content_schema.py")
            return 1
        print(f"{SCHEMA_PATH} is up to date")
        return 0

    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    SCHEMA_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {SCHEMA_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
