import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { BriefObjective } from '@tempo/core';
import { describe, expect, it } from 'vitest';
import { buildDeckModel, type BuildDeckInput } from './build.js';
import { parseEngineContent } from './engine-content.js';
import { buildDashboardFixture, buildEmptyDashboardFixture } from './fixtures/dashboard.js';
import type { Block, DeckModel, KpiTile, RoadmapRow } from './model.js';
import { defaultReportSpec, parseReportSpec } from './spec.js';

/**
 * `buildDeckModel` is snapshot-tested against **real engine output** (PRD §9
 * item 8): the fixture is a dump of an actual instant-tier run, regenerated by
 * `tempo-engine/scripts/dump_deck_fixture.py`. A hand-mocked payload would let
 * the engine's shape drift without a single test noticing.
 */

const RAW_CONTENT = JSON.parse(
  readFileSync(
    fileURLToPath(new URL('./fixtures/engine-content.gmv.instant.json', import.meta.url)),
    'utf8',
  ),
) as unknown;

function build(overrides: Partial<BuildDeckInput> = {}): DeckModel {
  const parsed = parseEngineContent(RAW_CONTENT);
  return buildDeckModel({
    content: parsed.content,
    contentVersion: parsed.version,
    dashboard: buildDashboardFixture(),
    spec: defaultReportSpec(BriefObjective.Gmv),
    objective: BriefObjective.Gmv,
    runId: 'run_fixture_gmv_instant',
    tier: 'instant',
    generatedAt: '2026-08-17T02:00:00.000Z',
    windowDays: 7,
    ...overrides,
  });
}

const blocksOf = (model: DeckModel, slideId: string): Block[] =>
  model.slides.find((s) => s.id === slideId)?.blocks ?? [];

const firstOfKind = <K extends Block['kind']>(blocks: Block[], kind: K) =>
  blocks.find((b): b is Extract<Block, { kind: K }> => b.kind === kind);

describe('buildDeckModel', () => {
  it('is pure — the same input builds an identical model', () => {
    expect(build()).toEqual(build());
  });

  it('builds the M2 slide frame in order', () => {
    expect(build().slides.map((s) => s.id)).toEqual(['s0', 's1', 's2', 's3', 's6', 'appendix-a']);
  });

  it('carries provenance the footer can print', () => {
    const { meta } = build();
    expect(meta.runId).toBe('run_fixture_gmv_instant');
    expect(meta.engineVersion).toBe('0.1.0');
    expect(meta.tier).toBe('instant');
    expect(meta.probesExecuted).toBe(0);
    expect(meta.legacyContent).toBe(false);
    expect(meta.period).toBe('10 Agu – 16 Agu');
  });

  describe('S1 KPI grid', () => {
    const grid = () => firstOfKind(blocksOf(build(), 's1'), 'kpiGrid');

    it('tiles the first six spec metrics as a 2x3', () => {
      expect(grid()?.layout).toBe('2x3');
      expect(grid()?.tiles).toHaveLength(6);
    });

    it('labels every tile in Bahasa, never with a metric key', () => {
      for (const tile of grid()!.tiles) {
        expect(tile.label).not.toBe(tile.metric);
        expect(tile.label.trim()).not.toBe('');
      }
    });

    it('applies the GMV objective label overrides', () => {
      const byMetric = new Map(grid()!.tiles.map((t: KpiTile) => [t.metric, t.label]));
      expect(byMetric.get('conversionValue')).toBe('Omzet (GMV)');
      expect(byMetric.get('conversions')).toBe('Pesanan');
    });

    it('grades ROAS from its band and leaves unbanded metrics to the delta', () => {
      const tiles = new Map(grid()!.tiles.map((t) => [t.metric, t]));
      // Fixture ROAS is well above 3x.
      expect(tiles.get('roas')?.light).toBe('green');
      // Every tile has a delta because the fixture has a prior period.
      expect(tiles.get('spend')?.delta).toMatch(/^[+-]/);
    });

    it('respects a per-client target over the band', () => {
      const spec = parseReportSpec(
        {
          ...defaultReportSpec(BriefObjective.Gmv),
          preset: 'custom',
          targets: { roas: 99 },
        },
        BriefObjective.Gmv,
      );
      const tiles = firstOfKind(blocksOf(build({ spec }), 's1'), 'kpiGrid')!.tiles;
      expect(tiles.find((t) => t.metric === 'roas')?.light).toBe('red');
    });
  });

  describe('S3 campaign table', () => {
    const table = () => firstOfKind(blocksOf(build(), 's3'), 'table')!.spec;

    it('grades each row and pairs the grade with an action', () => {
      for (const row of table().rows) {
        expect(['green', 'yellow', 'red', 'none']).toContain(row.light);
        if (row.light && row.light !== 'none') expect(row.action).toBeTruthy();
      }
    });

    it('names the outcome column for the objective', () => {
      expect(table().headers.at(-1)).toBe('Nilai Balik Belanja Iklan (ROAS)');
    });

    it('ranks campaigns by spend', () => {
      const rank = firstOfKind(blocksOf(build(), 's3'), 'chart')!.spec;
      const values = rank.series[0]!.values as number[];
      expect([...values].sort((a, b) => b - a)).toEqual(values);
    });
  });

  describe('S6 roadmap', () => {
    const rows = (): RoadmapRow[] => firstOfKind(blocksOf(build(), 's6'), 'roadmap')!.rows;

    it('carries every risk the engine raised, deduped', () => {
      const keys = rows().map((r) => `${r.action}::${r.evidenceRef}`);
      expect(new Set(keys).size).toBe(keys.length);
      expect(rows().length).toBeGreaterThan(0);
    });

    it('sorts P0 before P1 before P2', () => {
      const order = { P0: 0, P1: 1, P2: 2 } as const;
      const ranks = rows().map((r) => order[r.priority]);
      expect([...ranks].sort((a, b) => a - b)).toEqual(ranks);
    });

    it('caps P0 so the top band still means something', () => {
      const p0 = rows().filter((r) => r.priority === 'P0');
      expect(p0.length).toBeLessThanOrEqual(3);
      // Demotion is by magnitude, so what survives at P0 is the biggest share.
      expect(rows().length).toBeGreaterThan(p0.length);
    });

    it('states impact as a share, sourced from the finding magnitude', () => {
      for (const row of rows()) {
        expect(row.impact).toMatch(/^(\d+% dari belanja|—)$/);
        expect(row.evidenceRef).toBeTruthy();
      }
    });
  });

  describe('Lampiran A', () => {
    it('shows every spec metric per day, not just the tiled six', () => {
      const spec = defaultReportSpec(BriefObjective.Gmv);
      const table = firstOfKind(blocksOf(build(), 'appendix-a'), 'table')!.spec;
      expect(table.headers).toHaveLength(spec.metrics.length + 1);
      expect(table.rows).toHaveLength(7);
    });

    it('is omitted when the spec turns it off', () => {
      const spec = { ...defaultReportSpec(BriefObjective.Gmv) };
      spec.appendix = { ...spec.appendix, rawTable: false };
      expect(build({ spec }).slides.map((s) => s.id)).not.toContain('appendix-a');
    });
  });

  describe('honest empty states', () => {
    it('renders a deck with no ingested days rather than throwing', () => {
      const model = build({ dashboard: buildEmptyDashboardFixture() });
      expect(model.slides.map((s) => s.id)).toContain('s1');
      expect(model.meta.period).toBe('—');
      const table = firstOfKind(blocksOf(model, 's3'), 'table')!.spec;
      expect(table.rows).toEqual([]);
      expect(table.emptyNote).toBeTruthy();
    });

    it('records a fallback note when a section is written from templates', () => {
      // The fixture is an instant run, so every section is template-written.
      expect(build().meta.fallbacks.map((f) => f.reason)).toContain('deterministic_copy');
    });

    it('marks pre-M0 content as legacy and renders prose only', () => {
      const v1 = parseEngineContent({
        s1: { draft: { headline: 'Ringkasan lama.', summary: 'Isi.' }, source: 'llm', attempts: 1 },
        sections: {},
        s6: null,
      });
      const model = build({ content: v1.content, contentVersion: v1.version });
      expect(model.meta.legacyContent).toBe(true);
      expect(firstOfKind(blocksOf(model, 's6'), 'roadmap')!.rows).toEqual([]);
    });
  });
});
